spring:
  profiles:
    active: dev
  freemarker:
    template-loader-path: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
server:
  port: 9070

management:
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    root: info
    com.jte: info
    com.jte.sync2any.load.impl.CkLoadServiceImpl: debug