#【必填】同步目标elasticsearch的基本配置
elasticsearch:
    uris: 192.168.10.208:9200
    username: elastic
    password: changeme

#【必填】腾讯云CKAFKA配置
kafka:
  adress: 127.0.0.1:32768

#【必填】tdsql配置，可以配置多个数据库
mysql:
  datasources:
    -
      db-name: jte_pms_member
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true&allowMultiQueries=true&serverTimezone=Hongkong
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver

#【必填】配置同步到elasticsearch的基本规则
sync2any:
  #【选填】mysqldump工具的地址
  mysqldump: D:\program\mysql-5.7.25-winx64\bin\mysqldump.exe
  #【选填】监控告警（www.wangfengta.com），只有填写了此参数才能开启监控告警，具体配置参考下面章节
  alert:
    secret: aaaa
    app-id: bbbb
    delay-template-id: cccc
    idle-template-id: dddd
    error-template-id: eeee

  # 规则比较灵活，可以配置多个
  sync-config-list:
    -
      #【必填】要同步的TDSQL数据库名称
      db-name: member
      #【必填】要同步的表名，支持正则表达式，多个表名用逗号分隔
      sync-tables: "t_pms_checkin_log,t_pms_business_log,t_pms_account_log,t_pms_booking_log,t_pms_room_log,t_pms_unusual_log,t_pms_checkout_log,t_pms_member_log,t_pms_guest_log,t_pms_param_setting_log,t_pms_print_log,t_pms_sys_setting,t_pms_intermediary_log,t_pms_tour_team_log,t_pms_points_exchange_log,t_pms_lock_log,t_pms_clean_room_log,t_pms_buy_log,t_pms_approval_log,t_pms_agreement_unit_log,t_pms_pricesys_log,t_pms_ota_log,t_pms_metereading_log,t_pms_member_config_log,t_pms_log_table_sample,t_pms_housekeeping_audit_log,t_pms_constant_type_log,t_pms_commission_log,t_pms_commission_detail_log,t_pms_blacklist_log,t_pms_batch_import_log,t_pms_agreement_unit_price_strategy_log"
      #【选填】是否载入原始数据（0否，1是；默认开启【1】）
      dump-origin-data: 1
      mq:
        # 监听的CKAFKA的topic名称
        topic-name: test-t_member
        #【选填】消费者使用的topicGroup，如果不填写，则随机生成。每次重启本应用都会从kafka的"earliest"处开始读取。
        topic-group: local-test-consumer-group
      #【选填】此处可以配置TDSQL到elasticsearch的映射规则
      rules:
        -
          # 匹配此rule的表名，支持正则表达式
          table: t_member_order_[0-9]{10}
          # 自定义es的index名称
          index: t_member_order
          # 自定义同步到es的字段名称和字段类型(es的类型)，字段类型请参考类：com.jte.sync2any.model.es.EsDateType
          map: '{"group_code":"groupCode","user_code":",integer"}'
          # 字段过滤，多个字段用逗号分隔。如果有值，则只保留这里填写的字段。
          field-filter: "user_id,user_name"