#【必填】同步目标elasticsearch的基本配置
elasticsearch:
    uris: 192.168.10.208:9200
    username: elastic
    password: changeme

#【必填】腾讯云CKAFKA配置
kafka:
  adress: 127.0.0.1:32768

#【必填】tdsql配置，可以配置多个数据库
mysql:
  datasources:
    -
      db-name: jte_pms_member
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true&allowMultiQueries=true&serverTimezone=Hongkong
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver

#【必填】配置同步到elasticsearch的基本规则
sync2es:
  #【选填】mysqldump工具的地址
  mysqldump: D:\program\mysql-5.7.25-winx64\bin\mysqldump.exe
  #【选填】监控告警（www.wangfengta.com），只有填写了此参数才能开启监控告警，具体配置参考下面章节
  alert:
    secret: aaaa
    app-id: bbbb
    delay-template-id: cccc
    idle-template-id: dddd
    error-template-id: eeee

  # 规则比较灵活，可以配置多个
  sync-config-list:
    -
      #【必填】要同步的TDSQL数据库名称
      db-name: member
      #【必填】要同步的表名，支持正则表达式，多个表名用逗号分隔
      sync-tables: "t_member,t_member_order_[0-9]{10}"
      #【选填】延迟超过60秒，将会触发告警
      max-delay-in-second: 60
      #【选填】超过120分钟没接收到同步消息，将会触发告警
      max-idle-in-minute: 120
      #【选填】告警发生180分钟后，如果未恢复，则再次告警
      next-trigger-alert-in-minute: 180
      mq:
        # 监听的CKAFKA的topic名称
        topic-name: test-t_member
        #【选填】消费者使用的topicGroup，如果不填写，则随机生成。每次重启本应用都会从kafka的"earliest"处开始读取。
        topic-group: local-test-consumer-group
      #【选填】此处可以配置TDSQL到elasticsearch的映射规则
      rules:
        -
          # 匹配此rule的表名，支持正则表达式
          table: t_member_order_[0-9]{10}
          # 自定义es的index名称
          index: t_member_order
          # 自定义同步到es的字段名称和字段类型(es的类型)，字段类型请参考类：com.jte.sync2es.model.es.EsDateType
          map: '{"group_code":"groupCode","user_code":",integer"}'
          # 字段过滤，多个字段用逗号分隔。如果有值，则只保留这里填写的字段。
          field-filter: "user_id,user_name"